package model.bc.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 11 00:04:36 EET 2018
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    boolean checkLogin1(String userName, String password);

    boolean checkLogin2(String userName, String password);

    void getAllUserData1(String PatientName, String PASSWORD, String Gender);

    void getAllUserData2(String DoctorName, String PASSWORD, String Gender);
}

